/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianyy_Main */

#ifndef _Included_com_qianyy_Main
#define _Included_com_qianyy_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qianyy_Main
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qianyy_Main_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
